In [1]:
import gym
import numpy as np
import random
import matplotlib.pyplot as plt
%matplotlib inline

# 환경 불러오기

In [2]:
env = gym.make('FrozenLake-v0')

[2017-09-04 02:44:20,207] Making new env: FrozenLake-v0


In [3]:
#테이블을 모두 0으로 초기화한다
Q = np.zeros([env.observation_space.n,env.action_space.n])
#학습 매개변수를 설정한다
lr = .85
y = .99
num_episodes = 2000
#전체 보상과 각 에피소드의 단계를 저정할 리스트를 생성한다
#jList = []
rList = []
for i in range(num_episodes):
    #환경을 리셋하고 첫번째 새로운 관찰을 얻는다
    s = env.reset()
    rAll = 0
    d = False
    j = 0
    #Q-테이블 학습 알고리즘
    while j < 99:
        j+=1
        #Q-테이블로부터 (노이즈와 함께) 탐욕스럽게 선택함으로써 액션을 선택한다
        a = np.argmax(Q[s,:] + np.random.randn(1,env.action_space.n)*(1./(i+1)))
        #환경으로부터 새로운 상태와 보상을 얻는다
        s1,r,d,_ = env.step(a)
        #새로운 지식을 통해 Q-테이블을 업데이트한다
        Q[s,a] = Q[s,a] + lr*(r + y*np.max(Q[s1,:]) - Q[s,a])
        rAll += r
        s = s1
        if d == True:
            break
    #jList.append(j)
    rList.append(rAll)

In [4]:
print("Score over time: " +  str(sum(rList)/num_episodes))

Score over time: 0.324


In [5]:
print("Final Q-Table Values ")
print(Q)

Final Q-Table Values 
[[  6.13367454e-03   1.40393625e-01   5.04724681e-03   1.21177336e-02]
 [  1.22397831e-03   3.86955509e-04   1.32317073e-04   1.31470651e-01]
 [  1.19058192e-03   2.25117156e-03   1.02849194e-02   1.34036576e-01]
 [  2.91041211e-04   3.97851629e-04   1.88418974e-03   1.12323468e-01]
 [  2.12022830e-01   4.02596664e-04   2.62534683e-03   9.52571072e-05]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  1.10822110e-04   9.40874347e-06   1.52705174e-02   9.80056220e-07]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  3.82764703e-04   5.26436276e-05   5.74540534e-04   4.69255399e-01]
 [  7.05416208e-05   6.14194645e-01   1.29779601e-03   2.65724257e-03]
 [  6.37674107e-01   4.83045507e-05   1.60422098e-04   1.22231246e-03]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  2.48883160e-04   0.00000000e+00   8.68622041e-01   